; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_missile
	.word @sfx_ntsc_explosion

@sfx_ntsc_missile:
	.byte $8a,$05,$89,$33,$01,$89,$36,$01,$89,$39,$01,$89,$3a,$01,$89,$3c
	.byte $01,$89,$3d,$01,$89,$3e,$01,$89,$3f,$02,$89,$3e,$02,$89,$3d,$01
	.byte $89,$3c,$03,$89,$3b,$01,$89,$3a,$04,$89,$39,$03,$89,$38,$02,$89
	.byte $37,$03,$89,$36,$04,$89,$35,$04,$89,$34,$05,$89,$33,$06,$89,$32
	.byte $04,$89,$31,$04,$00
@sfx_ntsc_explosion:
	.byte $8a,$0f,$89,$3f,$01,$89,$3e,$04,$89,$3d,$03,$89,$3c,$04,$89,$3b
	.byte $01,$89,$3a,$02,$89,$39,$02,$89,$38,$01,$89,$37,$01,$89,$36,$02
	.byte $89,$35,$01,$89,$34,$02,$89,$33,$02,$89,$32,$02,$89,$31,$02,$00

.export sounds
