; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_maritime=music_data_maritime
.endif

music_data_maritime:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Maritime
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_maritime
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env2,@env3,@env5,@env1 ; 00 : Bass
	.word @env4,@env3,@env5,@env1 ; 01 : Lead
	.word @env0,@env3,@env6,@env1 ; 02 : Snare

@samples:

@env0:
	.byte $00,$ce,$c8,$c4,$c0,$00,$04
@env1:
	.byte $00,$c0,$7f,$00,$02
@env2:
	.byte $00,$cf,$7f,$00,$02
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $00,$cd,$cb,$c8,$c6,$00,$04
@env5:
	.byte $7f,$00,$00
@env6:
	.byte $c2,$7f,$00,$00

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ef, $47, $ff, $ef, $47, $bb, $82, $24, $d7, $00, $9b
	.byte $20, $9b, $1f, $9b, $47, $d9, $00, $9b, $1f, $b9, $20, $9b, $1d, $9b, $47, $bb, $24, $b9, $20, $9b, $00, $9b, $22, $9b
	.byte $1f, $9b, $47, $9d, $1b, $b9, $18, $9b, $1f, $9b, $00, $9b, $1d, $b9, $47, $bb, $1f, $9b, $20, $9b, $24, $9b, $27, $9b
	.byte $00, $9b, $2b, $9b, $47, $9d, $00, $9b, $24, $9b, $00, $9b, $27, $9b, $00, $9b, $29, $b9, $47, $bb, $24, $9b, $00, $9b
	.byte $27, $9b, $00, $9b, $22, $9b, $24, $9b, $47, $9d, $00, $9b, $19, $9b, $00, $9b, $1b, $9b, $00, $9b, $1d, $9b, $20, $9b
	.byte $47, $f7, $00, $b9, $24, $9b, $27, $9b, $47, $ff, $b3, $00, $9b, $24, $9b, $47, $00, $9b, $2c, $d7, $29, $f5, $47, $d9
	.byte $00, $9b, $22, $b9, $24, $9b, $25, $9b, $47, $ff, $95, $00, $9b, $20, $9b, $1f, $9b, $47, $ff, $95, $00, $9b, $1b, $9b
	.byte $1d, $9b, $47, $ff, $ef, $47, $00, $ff, $ed, $47, $ff, $ef, $47, $ff, $ef, $47, $ff, $ef, $47, $ff, $ef, $47, $34, $81
	.byte $35, $ff, $8f, $37, $d7, $47, $33, $ff, $93, $00, $9b, $30, $9b, $2e, $9b, $47, $30, $ff, $ed, $47, $00, $9b, $2e, $b9
	.byte $00, $9b, $2b, $b9, $2c, $9b, $29, $9b, $47, $bb, $2c, $9b, $30, $ff, $93, $47, $ff, $95, $00, $95, $2f, $83, $30, $9b
	.byte $2c, $9b, $47, $2e, $b9, $2c, $9b, $2b, $ff, $93, $47, $00, $b9, $25, $9b, $27, $9b, $29, $9b, $2c, $b9, $2b, $9b, $47
	.byte $29, $b9, $2c, $9b, $30, $ff, $93, $47, $d9, $00, $d7, $29, $9b, $27, $9b, $47, $24, $ff, $b1, $22, $9b, $24, $9b, $47
	.byte $25, $d7, $24, $9b, $20, $9b, $00, $9b, $1f, $9b, $00, $9b, $47, $1d, $f5, $00, $b9, $20, $9b, $22, $9b, $47, $f7, $00
	.byte $b9, $20, $9b, $24, $9b, $47, $ff, $95, $00, $9b, $1d, $9b, $1f, $9b, $47, $f7, $00, $b9, $1b, $9b, $19, $9b, $47, $ff
	.byte $95, $00, $9b, $18, $9b, $14, $9b, $47, $ff, $95, $00, $9b, $13, $9b, $11, $9b, $47, $ff, $ef, $47, $00, $ff, $ed, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $ef, $ff, $ef, $f7, $82, $20, $9b, $00, $9b, $1d, $9b, $1b, $9b, $d9, $00, $9b, $1b, $b9, $1d, $9b, $18, $9b, $bb
	.byte $00, $ff, $b1, $ff, $b3, $18, $b9, $bb, $00, $ff, $93, $27, $9b, $9d, $00, $ff, $93, $24, $b9, $bb, $00, $ff, $b1, $bb
	.byte $14, $9b, $00, $9b, $16, $9b, $00, $9b, $18, $9b, $1d, $9b, $f7, $00, $d7, $24, $9b, $ff, $b3, $00, $b9, $f7, $24, $f5
	.byte $d9, $00, $f5, $20, $9b, $ff, $95, $00, $b9, $1b, $9b, $ff, $95, $00, $b9, $18, $9b, $ff, $ef, $00, $ff, $ed, $ff, $ef
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $95, $33, $d7, $2e, $ff, $93, $00, $d7, $2b, $ff, $ed, $9d, $00, $ff, $b1, $24, $9b
	.byte $bb, $29, $9b, $2c, $ff, $93, $ff, $95, $00, $d7, $2b, $b9, $24, $9b, $27, $ff, $93, $00, $ff, $ed, $24, $b9, $27, $9b
	.byte $2c, $ff, $93, $d9, $00, $ff, $93, $1f, $ff, $b1, $00, $b9, $20, $d7, $00, $ff, $93, $25, $f5, $00, $d7, $27, $9b, $f7
	.byte $00, $d7, $29, $9b, $ff, $95, $00, $b9, $18, $9b, $f7, $00, $d7, $1d, $9b, $ff, $95, $00, $b9, $1d, $9b, $ff, $95, $00
	.byte $b9, $0c, $9b, $ff, $ef, $ff, $d1, $00, $9b, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ff, $ef, $ff, $ef, $80, $1d, $ff, $ed, $1b, $ff, $b1, $18, $b9, $11, $ff, $ed, $f7, $00, $b9, $14, $b9, $1d, $ff, $ed
	.byte $1b, $ff, $b1, $20, $8d, $1f, $8b, $1d, $8d, $1b, $8b, $1d, $ff, $ed, $82, $14, $d7, $00, $9b, $14, $9b, $00, $9b, $18
	.byte $b9, $80, $19, $ff, $ed, $18, $ff, $b1, $00, $b9, $1d, $ff, $b1, $16, $b9, $18, $ff, $ed, $19, $ff, $ed, $1b, $ff, $ed
	.byte $11, $ff, $ed, $82, $11, $ff, $ed, $00, $9b, $80
@song0ref643:
	.byte $11, $9b, $00, $9b, $11, $9b, $00, $9b, $11, $9b, $00, $9b, $11, $9b, $00, $9b, $11, $9b, $00, $9b, $11, $9b, $00, $9b
	.byte $11, $9b, $00, $9b, $11, $9b, $00, $9b, $0c, $9b, $00, $9b, $0c, $9b, $00, $9b, $0c, $9b, $00, $9b, $0c, $9b, $00, $9b
	.byte $0d, $9b, $00, $9b, $0d, $9b, $00, $9b, $07, $9b, $00, $9b, $07, $9b, $00, $9b
	.byte $41, $38
	.word @song0ref643
	.byte $13, $9b, $00, $9b, $13, $9b, $00, $9b
	.byte $41, $38
	.word @song0ref643
	.byte $13, $9b, $00, $9b, $13, $9b, $00, $9b
	.byte $41, $38
	.word @song0ref643
	.byte $0f, $9b, $00, $b9, $82, $0d, $ff, $ed, $0f, $ff, $ed, $11, $ff, $ed, $0c, $ff, $ed, $0d, $ff, $ed, $0c, $ff, $ed, $11
	.byte $ff, $ed, $11, $ff, $eb, $00, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $84
@song0ref767:
	.byte $03, $8d, $03, $8b, $03, $8d, $03, $8b, $03, $8d, $03, $8b, $03, $8d, $03, $8b, $03, $8d, $03, $8b, $03, $8d, $03, $8b
	.byte $03, $8d, $03, $8b, $03, $8d, $03, $8b, $03, $8d, $03, $8b, $03, $8d, $03, $8b
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $41, $28
	.word @song0ref767
	.byte $03, $8d, $03, $8b, $03, $8d, $03, $8b, $00, $d7, $82
@song0ref896:
	.byte $03, $85, $00, $85, $03, $83, $00, $85, $03, $85, $00, $93, $03, $85, $00, $93, $03, $8d, $00, $a9, $d7, $03, $83, $00
	.byte $87, $03, $83, $00, $85, $03, $83, $00, $95, $03, $83, $00, $95, $03, $8d, $00, $ab, $db, $03, $85, $00, $85, $03, $83
	.byte $00, $85, $03, $85, $00, $93, $03, $85, $00, $93, $03, $8d, $00, $a7, $d7, $03, $83, $00, $87, $03, $83, $00, $85, $03
	.byte $83, $00, $95, $03, $83, $00, $95, $03, $8d, $00, $ab, $d9, $03, $85, $00, $85, $03, $83, $00, $85, $03, $85, $00, $93
	.byte $03, $85, $00, $93, $03, $8d, $00, $a9, $d9, $03, $85, $00, $85, $03, $83, $00, $85, $03, $85, $00, $93, $03, $85, $00
	.byte $93, $03, $8d, $00, $a9, $d9
	.byte $41, $29
	.word @song0ref896
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref1029:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $41, $28
	.word @song0ref1029
	.byte $ff, $ef, $ff, $ef, $42
	.word @song0ch4loop
