; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_titan=music_data_titan
.endif

music_data_titan:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Titan
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_titan
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env7,@env2,@env6,@env0 ; 00 : Bass
	.word @env1,@env2,@env5,@env0 ; 01 : Lead
	.word @env3,@env2,@env4,@env0 ; 02 : Snare

@samples:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$ce,$cd,$cc,$ca,$c8,$c6,$c5,$c3,$c2,$06,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$02,$c3,$c4,$c5,$c6,$c7,$c8,$c7,$c6,$c5,$c5,$c4,$c3,$c2,$03,$c3,$c4,$c4,$c5,$c6,$c6,$c7,$c8,$c7,$c6,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$02,$c2,$c2,$c3,$c3,$c4,$c4,$c5,$c4,$c4,$c3,$c2,$c2,$c1,$02,$c2,$c2,$c3,$c3,$c2,$02,$c1,$00,$4e
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $00,$cf,$c5,$c0,$00,$03
@env4:
	.byte $7f,$00,$00
@env5:
	.byte $c2,$7f,$00,$00
@env6:
	.byte $c1,$7f,$00,$00
@env7:
	.byte $00,$cf,$02,$ce,$09,$cd,$0a,$cc,$0c,$cb,$0e,$ca,$0d,$c9,$09,$c8,$08,$c7,$0c,$c6,$0a,$c5,$07,$c4,$09,$c3,$09,$c2,$0e,$c1,$12,$c0,$00,$1f

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song0ref6:
	.byte $0a, $b9, $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47, $0d, $b9, $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47
	.byte $bb, $47, $0c, $b9, $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47, $05, $b9, $47, $bb, $47, $bb, $47, $bb, $47
	.byte $bb, $47, $bb, $47
	.byte $41, $1c
	.word @song0ref6
	.byte $47, $06, $b9, $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47, $08, $b9, $47, $bb, $47, $bb, $47, $bb, $47, $bb
	.byte $47, $bb, $47, $0a, $b9, $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47, $9d, $03, $9b, $47, $05, $b9, $47, $bb, $47, $bb
	.byte $47, $bb, $47, $bb, $47, $03, $9b, $05, $9b, $47, $06, $b9, $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47, $00, $9b, $05
	.byte $9b, $47, $01, $b9, $47, $bb, $47, $bb, $47, $40, $0c, $b9, $47, $bb, $47, $bb, $47, $40, $0a, $b9, $47, $bb, $47, $bb
	.byte $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47, $bb, $47, $00, $b9, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref180:
	.byte $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $82
	.byte $1d, $9b, $20, $9b, $22, $b9, $bb, $bb, $bb, $bb, $9d, $1d, $9b, $29, $b9, $bb, $bb, $bb, $bb, $27, $9b, $25, $9b, $2b
	.byte $b9, $bb, $bb, $bb, $18, $b9, $1b, $b9, $21, $b9, $bb, $bb, $bb, $bb, $15, $b9, $16, $b9, $bb, $bb, $bb, $1b, $b9, $19
	.byte $b9, $18, $b9, $bb, $bb, $bb, $1d, $b9, $1b, $b9, $19, $b9, $bb, $bb, $bb, $18, $b9, $19, $b9, $21, $b9, $bb, $bb, $bb
	.byte $bb, $00, $9b, $15, $9b, $22, $b9, $bb, $bb, $bb, $bb, $1d, $9b, $1b, $9b, $25, $b9, $bb, $bb, $24, $b9, $bb, $bb, $22
	.byte $b9, $bb, $bb, $bb, $00, $b9, $bb, $bb, $bb, $bb, $bb, $bb, $bb, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $41, $17
	.word @song0ref180
	.byte $41, $17
	.word @song0ref180
	.byte $41, $17
	.word @song0ref180
	.byte $41, $17
	.word @song0ref180
	.byte $bb, $bb, $bb, $bb, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $84
@song0ref338:
	.byte $40, $4f, $b9, $00, $9d, $40, $4f, $91, $00, $85, $40, $4f, $91, $00, $83, $40, $4f, $93, $00, $85, $40, $4f, $81, $8f
	.byte $00, $a9, $40, $4f, $91, $00, $a5, $40, $4f, $a5, $00, $91
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $41, $1d
	.word @song0ref338
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $17
	.word @song0ref180
	.byte $41, $17
	.word @song0ref180
	.byte $41, $17
	.word @song0ref180
	.byte $41, $17
	.word @song0ref180
	.byte $bb, $bb, $bb, $bb, $42
	.word @song0ch4loop
